version: '3'

services:
  boilerplate:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - .:/boilerplate:cached

    command: /bin/sh -c "while sleep 1000; do :; done"
